onboard tiltProfiles
2DegreesInvesting/tiltDataPipelines pull request #114
Opened 2023-12-26 11:35 UTC by SKruthoff

This is the code that was used to onboard the results of the profiles. For now it is not completed, but wanted to create it to have a first look.

2024-01-10 14:50 UTC, ysherstyuk requested changes
Looks good, I had two comments only. Also did you generate the tables?

2024-01-10 14:50 UTC, ysherstyuk commented on functions/processing.py
> +        ecoinvent_licenced = ecoinvent_licenced.distinct()
why do we need .distinct() on ecoinvent data?

2024-01-10 14:50 UTC, ysherstyuk commented on functions/tables.py
> +        'location': 'wrapperOutput/emission_profile_company',
You partition by batch, but in processing.py you also remove the batch column. How does that exactly work?

2024-01-10 14:52 UTC, SKruthoff commented on functions/processing.py
> +        ecoinvent_licenced = ecoinvent_licenced.distinct()
I dont know which records are duplicated to be honest, but I know that it threw an error when I was trying to regenerate it, so I included it here.

2024-01-10 14:56 UTC, SKruthoff commented on functions/tables.py
> +        'location': 'wrapperOutput/emission_profile_company',
Since we ran the input in batches we partitioned the output of the wrapper in batches as well. This however is not what we want in our tables in the raw layer. That is why we remove the column as well as the partition column from the tables in the raw layer. 

Here you can see that the output of the wrapper is partitioned by the batch:
![image](https://github.com/2DegreesInvesting/tiltDataPipelines/assets/137387900/24403228-28b1-47cb-98d1-a4cda8b83096)

This is not something that we have to specify when reading in the table itself. However we do not want to keep this in the table that ends up in the raw layer. That is why we drop that partition column when transferring it from the landingzone to the raw layer.

2024-01-11 07:34 UTC, SKruthoff commented on functions/processing.py
> +        ecoinvent_licenced = ecoinvent_licenced.distinct()
Removed the code, because the data does not contain duplicates.

2024-01-11 08:22 UTC, ysherstyuk commented on functions/tables.py
> +        'location': 'wrapperOutput/emission_profile_company',
That I understand, so we first process data in batches and then we delete the batch column

2024-01-11 08:23 UTC, merged