New schema for LDM_v1
2DegreesInvesting/tiltDataPipelines pull request #120
Opened 2024-01-29 16:11 UTC by ysherstyuk

Hi @SKruthoff,

I have implemented table definitions for all tables based on the latest version of the normalized LDM [here](https://app.diagrams.net/#G1lx8d7Y-K93jZ0OGd1L3j0flsXxUipK2w#%7B%22pageId%22%3A%22l5rHDVNY7WpBq-mbxrBs%22%7D). 
I have kept all layers from ecoinvent data for now, which means some of the transform and related tables are still there. We might also need to check if we still need to keep all table definitions starting from ep_ei_matcher_landingzone.

2024-01-31 08:44 UTC, SKruthoff reviewed
Two things that I noted that would be important to fix for now:
- Column naming should be consistent, f.ex. the reduction targets have names in all capital letters which we should avoid. I am find with keeping it consistent with the rest of the columns
- I ran into some thing when reading from and writing to delta tables, so I would suggest that we remove it from your PR and I will submit mine in a bit.

2024-01-31 08:44 UTC, SKruthoff commented on functions/tables.py
> +        'companies_categories_datamodel': {
Category is not very descriptive, what information is behind it? Are the multiple categories that a company can have?

2024-01-31 08:44 UTC, SKruthoff commented on functions/tables.py
> +        'products_lookup_datamodel': {
I would rather call this products and not products_lookup, since in the end this table contains the information around the unique products.

2024-01-31 08:44 UTC, SKruthoff commented on functions/tables.py
> +        'main_activity_ecoinvent_mapper_raw': {
Do we want to keep the naming of activity? To me it is a bit vague what should be contained in here or is it just the reseller or manufacturer information?

2024-01-31 08:44 UTC, SKruthoff commented on functions/tables.py
> +        'geography_ecoinvent_mapper_raw': {
Maybe you dont know, but are things like the priority and input priority specific for the methodology that exists right now or are they generic?

2024-01-31 08:44 UTC, SKruthoff commented on functions/tables.py
> +        'scenario_targets_IPR_raw': {
Whitespaces can not exist in managed storage.

2024-01-31 08:58 UTC, ysherstyuk commented on functions/tables.py
> +        'companies_categories_datamodel': {
Good question, category actually doesn't exist on its own. There is only category_id which is sha value generated from a combination of three columns: group, sector and subsector. And I believe a company can only belong to one group. Do you think it's confusing to keep category_id then?

2024-01-31 09:05 UTC, ysherstyuk commented on functions/tables.py
> +        'products_lookup_datamodel': {
Alright

2024-01-31 09:11 UTC, ysherstyuk commented on functions/tables.py
> +        'main_activity_ecoinvent_mapper_raw': {
I think we do. It is more than just reseller/manufacturer. These are all options from EP that are then mapped to a few options of ecoinvent: 'agent/ representative', 'distributor', 'manufacturer/ producer', 'multi-category', 'retailer', 'service provider', 'subcontractor', 'wholesaler'. So imo, it must be general. However, once we have other sources, we need to see whether main activity information is provided and in which format it is. I would say for now we can keep it as it is, and if necessary, we will adjust

2024-01-31 09:13 UTC, ysherstyuk commented on functions/tables.py
> +        'geography_ecoinvent_mapper_raw': {
From what I know it is based on the methodology that Mirja created some time ago, so there was some logic behind why there are certain priorities and how they need to be categorised. But for input_priority i don't know, I will ask around.

2024-01-31 09:15 UTC, ysherstyuk commented on functions/tables.py
> +        'scenario_targets_IPR_raw': {
Will adjust and keep the origional names

2024-01-31 09:22 UTC, ysherstyuk commented on functions/tables.py
> +        'geography_ecoinvent_mapper_raw': {
Input_priority is used in prioritizing input products and it needs to be reversed according to some methodology created by Anne

2024-01-31 10:08 UTC, SKruthoff commented on functions/tables.py
> +        'companies_categories_datamodel': {
Do we know if it is used for anything else in the process somewhere? Otherwise I would remove it to be honest

2024-01-31 10:11 UTC, SKruthoff commented on functions/tables.py
> +        'main_activity_ecoinvent_mapper_raw': {
Fair, then I would still choose for a column name that is a bit more descriptive than main activity, because imo that can also be interpreted as a product they produce f.ex. Maybe something like business type instead of main_activity is more descriptive?

2024-01-31 10:11 UTC, SKruthoff commented on functions/tables.py
> +        'geography_ecoinvent_mapper_raw': {
Okay, for now it is fine like this I think

2024-01-31 10:51 UTC, ysherstyuk commented on functions/tables.py
> +        'main_activity_ecoinvent_mapper_raw': {
Fair

2024-01-31 10:56 UTC, ysherstyuk commented on functions/tables.py
> +        'companies_categories_datamodel': {
Good point actually, indeed category_id and group are not used anywhere

2024-01-31 11:02 UTC, ysherstyuk commented on functions/tables.py
> +        'companies_categories_datamodel': {
Also sectors and sunsectors are not used, so I'll remove this table

2024-01-31 13:22 UTC, SKruthoff requested changes
Only two small changes that I think should be handy.

2024-01-31 13:22 UTC, SKruthoff commented on functions/tables.py
> +                StructField('business_type_id', StringType(), False),
I think I placed the comment wrong in the earlier review. I mean that this would only be applied from the data model layer. In the landingzone and raw layer we would keep the old names.

2024-01-31 13:22 UTC, SKruthoff commented on functions/tables.py
> +            'columns':  StructType([
so far I replaced the non allowed characters with _ so it might be good to keep that for consistency

2024-01-31 13:31 UTC, ysherstyuk commented on functions/tables.py
> +                StructField('business_type_id', StringType(), False),
Hm, I kept main_activity in the original tables, which is companies. However, mappers we load as they are to the landingzone, then raw etc. What do you say?

2024-01-31 13:32 UTC, ysherstyuk commented on functions/tables.py
> +            'columns':  StructType([
Ah can we then merge your PR first and keep your version when resolving merge conflict, so I don't have to change it back and forth haha

2024-02-01 14:10 UTC, SKruthoff requested changes
I would double check that the merge of the develop branch and your local version of the branch went alright. I see that f.ex. the writing and reading of a table is still is in the version of your branch and not the recently merged develop branch. 

Additionally, I would double check the replacing of whitespaces. I see that you have just removed them but we said that all whitespaces and special characters in delta tables are replaced with underscores.

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +            'location': 'countries_mapper',
I think this should still be the location of the csv file.

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +                StructField('GeographicalClassification', StringType(), True),
We said that whitespaces would be replaced by _ so here I would expect the name Geographical_Classification.

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +                StructField('GeographicalClassification', StringType(), True),
Same as comment above

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +         'ecoinvent_cut_off_datamodel': {
This should be the structure of the tables that I have defined and not the one you have defined earlier.

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +        'ecoinvent-v3.9.1_co2_data_landingzone': {
Do we not want to make an export of the actual source file instead of the file that they have subfiltered and merged?

2024-02-01 14:10 UTC, SKruthoff commented on functions/tables.py
> +        'ep_ei_matcher_eurocaps_landingzone': {
I dont know if we need to include the eurocaps mapper in the data. It was mainly a one off thing, so I would not onboard it.

2024-02-01 14:13 UTC, ysherstyuk commented on functions/tables.py
> +                StructField('GeographicalClassification', StringType(), True),
Yes, I thought that should have happened with the merge right? I did pull the changes.

2024-02-01 15:13 UTC, ysherstyuk commented on functions/tables.py
> +        'ecoinvent-v3.9.1_co2_data_landingzone': {
Yes, you are right

2024-02-02 15:17 UTC, SKruthoff approved these changes
LGTM!

2024-02-02 15:17 UTC, merged