Onboard tilt ledger
2DegreesInvesting/tiltDataPipelines pull request #132
Opened 2024-05-08 09:54 UTC by SKruthoff

Hi,

this is a quite huge PR since it builds on the work of the last weeks. Lets discuss this together but the highlights are some changes to the way we calculate the empty values for the signalling checks, onboarding of tiltLedger and Company.info and some changes to the datamodel data of ecoinvent.

Cheers,
Sven

2024-05-22 14:23 UTC, SKruthoff commented on functions/data_quality_functions.py
> +def calculate_filled_values(dataframe: DataFrame, spark_session: SparkSession) -> DataFrame:
adapt docstring

2024-05-22 14:27 UTC, SKruthoff commented on functions/processing_raw.py
> +            'Kamer_van_Koophandel_nummer': 'kvk_number', 'RSIN_nummer': 'rsin_number', 'Instellingsnaam': 'default_compnay_name', 'Statutaire_naam': 'statutory_compnay_name', 'Handelsnaam_1': 'trade_
Use the 12 digit kvk number as the kvk number, which then makes it unique

2024-05-27 13:25 UTC, ysherstyuk requested changes
Looking good. I have pasted a few comments, some of them we already discussed.

2024-05-27 13:25 UTC, ysherstyuk commented on functions/processing_raw.py
> +        rename_dict = {
If I'm not mistaken, we rename columns only starting from datamodel layer

2024-05-27 13:25 UTC, ysherstyuk commented on functions/tables.py
As discussed, we need to adjust tables.py to the new table structure

2024-05-27 13:25 UTC, ysherstyuk commented on functions/tables.py
> +        'companies_company_info_raw': {
Do we rename columns already in the raw layer? I thought it was from the datamodel layer

2024-05-27 13:25 UTC, ysherstyuk commented on tests/test_dataframe_helpers.py
Did you manage to test new functionality?

2024-05-27 13:25 UTC, ysherstyuk commented on functions/processing_datamodel.py
> +        # TODO: I dont think we should take the from date in here, since that might change the product id if something arbitrary in the other columns changes
Good point. I think the part on generating product data here can be deleted, since we need to write Sohail's processed products, with the assumption that product_id is generated in his part

2024-05-27 13:25 UTC, ysherstyuk commented on functions/processing_datamodel.py
> +        # TODO: I dont know if we have to reuse the product id created in the products datamodel table, because we can just repoduce it based on the same information
Do we need to create an action item from it?

2024-05-27 13:25 UTC, ysherstyuk commented on functions/processing_datamodel.py
> +        cut_off_ao_raw.data = cut_off_ao_raw.data.withColumn("CPC_code", F.trim(F.split("CPC_Classification", ":")[0]))
What are you trying to do here?

2024-05-29 08:05 UTC, SKruthoff commented on functions/processing_datamodel.py
> +        # TODO: I dont think we should take the from date in here, since that might change the product id if something arbitrary in the other columns changes
Products datamodel is deleted.

2024-05-29 08:07 UTC, SKruthoff commented on functions/processing_datamodel.py
> +        cut_off_ao_raw.data = cut_off_ao_raw.data.withColumn("CPC_code", F.trim(F.split("CPC_Classification", ":")[0]))
Get the columns that are related to the activity in the ecoinvent data. This is a custom select function to preserve the map function in the background.

2024-05-29 08:11 UTC, SKruthoff commented on functions/processing_datamodel.py
> +        # TODO: I dont know if we have to reuse the product id created in the products datamodel table, because we can just repoduce it based on the same information
No I have also deleted it. since this is connected to the products table that I have deleted.

2024-05-29 08:13 UTC, SKruthoff commented on functions/processing_datamodel.py
> +        cut_off_ao_raw.data = cut_off_ao_raw.data.withColumn("CPC_code", F.trim(F.split("CPC_Classification", ":")[0]))
That CPC code column consists of the code and the description separated by a :. So I am splitting that column by the separator and choose the first item of the split. I use the trim function to make sure that there are no leading or trailing whitespaces. Not sure if this is 100% necessary but there is probably some sense behind it.

2024-05-29 12:24 UTC, ysherstyuk commented on functions/processing_datamodel.py
> +        # TODO: I dont think we should take the from date in here, since that might change the product id if something arbitrary in the other columns changes
Hm you mean from the catalog or?

2024-05-29 14:58 UTC, ysherstyuk approved these changes
Looks good! There was only a small typo:)

2024-05-29 15:13 UTC, merged