Restructure table definitions
2DegreesInvesting/tiltDataPipelines pull request #133
Opened 2024-05-16 09:02 UTC by ysherstyuk

Hi @SKruthoff,

The main goal of this change is restructuring table definition for more efficient processing. For now only restructuring table.py where we specify schema into separate layers.

2024-05-17 09:19 UTC, SKruthoff requested changes
In general it looks good. I have some specific questions around some functionality and some files that are added or deleted need to be reversed into the state of the dev branch

2024-05-17 09:19 UTC, SKruthoff commented on .vscode/settings.json
Remove this file from the PR, this is only a local file and should not be in the repo

2024-05-17 09:19 UTC, SKruthoff commented on requirementsuninstall.txt
remove the file even though it is empty

2024-05-17 09:19 UTC, SKruthoff commented on uninstall.txt
remove this file as well

2024-05-17 09:19 UTC, SKruthoff commented on settings.yaml
Add the template for the settings again, because that file should still be present in the branch

2024-05-17 09:19 UTC, SKruthoff commented on functions/database.py
> +      for layer in all_table_definitions:
Is this loop necessary? We already know the schema name and we are not really looping over anything here.

2024-05-17 09:19 UTC, SKruthoff commented on functions/datamodel_schema.py
> +            'quality_checks': [['unique', ['activity_uuid']]]
This is a bit tricky, since the develop branch is further than this branch. The definition of the quality checks should also be in a dictionary format and not in the old list format.

2024-05-17 09:19 UTC, SKruthoff commented on functions/monitoring_schema.py
Are there no more tables in the monitoring schema. I vaguely remember a test table or something but we might have removed that one along the way.

2024-05-17 09:19 UTC, SKruthoff commented on functions/monitoring_schema.py
Did we check that we can generate all tables?

2024-05-17 14:00 UTC, ysherstyuk reviewed
> Are there no more tables in the monitoring schema. I vaguely remember a test table or something but we might have removed that one along the way. 

There are indeed test tables. One is currently in the landingzone and one is in the raw layer, corresponding with test names of these tables. I see they are also used in testing, but not in the main environment right? So they don't need to be mentioned separately in the dictionary?

2024-05-21 08:41 UTC, SKruthoff commented
> > Are there no more tables in the monitoring schema. I vaguely remember a test table or something but we might have removed that one along the way.
> 
> There are indeed test tables. One is currently in the landingzone and one is in the raw layer, corresponding with test names of these tables. I see they are also used in testing, but not in the main environment right? So they don't need to be mentioned separately in the dictionary?

If they are used in testing we also need them in the dictionaries, since we also want to run the tests.

2024-05-22 11:37 UTC, ysherstyuk commented on functions/datamodel_schema.py
> +            'quality_checks': [['unique', ['activity_uuid']]]
This is fixed now

2024-05-22 11:42 UTC, ysherstyuk commented
@SKruthoff I have made adjustments to my PR. All issues mentioned above are fixed. I have merged develop into my branch with all data quality checks changes.

2024-05-22 12:47 UTC, SKruthoff approved these changes
Looks good.

2024-05-22 12:47 UTC, merged