Onboarding-ecoinvent-new-version_v10
2DegreesInvesting/tiltDataPipelines pull request #136
Opened 2024-06-17 16:44 UTC by ysherstyuk

Hi Sven,

All ecoinvent data from v10 are onboarded, including the remaining tables from database_overview, cut_off_cumulative_LCIA_v3.10 to both raw layer and where relevant to datamodel layer. 

The generation of all tables is tested and all of them are available in the Catalog.

Only input_data is not onboaded because we don't have it yet. However it is not a priority for now, we will add it in the upcoming weeks once the data is available.

2024-06-19 14:03 UTC, SKruthoff requested changes
Hi, see my comments. In general it looks good, just double checking two things. The HS observation in cut-off overview is based on the finding from Sohail, so maybe good to check the other AOs if they also have that column and not just the APSOS ao.

2024-07-08 13:21 UTC, ysherstyuk commented on functions/datamodel_schema.py
> +            StructField('CPC_name', StringType(), True),
These are lowercase in the Catalog. Do I need to change it here to lowercase then?

2024-07-08 13:23 UTC, ysherstyuk commented on functions/landingzone_schema.py
>          ]
Hm I think I was adding everything based on the new setup of the data. Can you elaborate what you mean by HS Classification?

2024-07-08 14:47 UTC, ysherstyuk commented on functions/datamodel_schema.py
> +            StructField('CPC_name', StringType(), True),
Done! Changed to lowercase

2024-07-08 21:20 UTC, SKruthoff requested changes
There is only one minor change that still needs to be made. Feel free to let someone else (like Alex) approve it once that change is made, to cross off this branch.

2024-07-08 21:20 UTC, SKruthoff commented on functions/landingzone_schema.py
> +            StructField('HS2017_Classification', StringType(), True),
The HS Classification does not have an underscore in their name in the landingzone. In the raw schema it should have it though.

2024-07-11 09:46 UTC, ysherstyuk commented on functions/landingzone_schema.py
> +            StructField('HS2017_Classification', StringType(), True),
Good point!

2024-08-02 11:27 UTC, SKruthoff approved these changes

2024-08-02 11:27 UTC, merged