Update schema
2DegreesInvesting/tiltDataPipelines pull request #149
Opened 2024-08-07 21:39 UTC by EuiYeonJang

This PR updates the following schemas to include the necessary data quality framework scores:
- `companies_datamodel` to include `data_granularity` score
- `tiltLedger_mapping_datamodel` (newly created for the datamodel layer)
- `tiltLedger_datamodel` to include `model_certainty` score
- `sources_mapper_datamodel` to include `data_source_reliability` score

2024-08-07 21:43 UTC, EuiYeonJang commented on functions/processing_datamodel.py
> +        companies_raw_final.data = companies_raw_final.data.join(
Could you please pay a special attention this line? If I use the custom_join, the code errors due to the mapping column missing

2024-08-07 21:43 UTC, EuiYeonJang commented
Please be advised: unfortunately, a lot of changes reflected in the files include formatting changes

2024-08-08 09:00 UTC, SKruthoff commented on functions/processing_datamodel.py
> +        companies_raw_final.data = companies_raw_final.data.join(
Yes the map column is going missing due to the group by function. I have also implemented a custom_average function for the code that Sohail needs. The issue here is that in an aggregation you would not only want to concat the strings, but you would also want to concatenate the values in the map column that you are grouping by. Do you want to take a shot at implementing it yourself with some examples/ideas from my side?

2024-09-09 09:39 UTC, SKruthoff commented
Can you maybe point me to the code that needs to be reviewed specifically? I see no flaw in the code, but the changes in formatting make it hard to check it properly.

2024-10-02 11:53 UTC, SKruthoff requested changes
In principle I agree that this PR is correct. I would again check that all parts that are contained in this PR are still relevant. Specifically the custom_concatenate can be removed I think.

2024-10-02 11:53 UTC, SKruthoff commented on functions/custom_dataframes.py
> +    def custom_concatenate(
Is this still relevant?

2024-10-08 07:14 UTC, SKruthoff approved these changes
Looks good to me!

2024-10-08 07:29 UTC, merged