Include refactoring steps + scope data into develop branche
2DegreesInvesting/tiltDataPipelines pull request #182
Opened 2024-10-09 14:32 UTC by drelsabrouty

2024-10-09 15:08 UTC, SKruthoff requested changes

2024-10-09 15:08 UTC, SKruthoff commented on indicators.py
> +    # generate_table_enriched_datamodel("emission_profile_ledger_upstream_enriched")
Comment back in

2024-10-09 15:08 UTC, SKruthoff commented on ecoInvent.py
> +    # generate_table_raw('scope_2_mandatory_ghgs_raw')
Comment back in

2024-10-11 09:47 UTC, drelsabrouty reviewed
fixed

2024-10-11 09:47 UTC, drelsabrouty reviewed
fixed

2024-10-11 09:50 UTC, drelsabrouty reviewed
fixed

2024-10-15 12:12 UTC, EuiYeonJang approved these changes
It looks fine, I just don't know about leaving print statements

2024-10-15 12:20 UTC, merged