Data quality checks
2DegreesInvesting/tiltDataPipelines pull request #20
Opened 2023-07-21 06:35 UTC by SKruthoff

2023-07-21 06:38 UTC, SKruthoff commented
This is related to issue #11 to implement a framework for data quality checks. Additionally, I have adapted the name of the unidentifies_ao tables to undefined_ao tables

2023-07-21 06:44 UTC, SKruthoff commented
When testing some pipeline I ran into an issue, so please do not merge yet.

2023-07-31 12:06 UTC, ysherstyuk requested changes
I left a few comments and questions. Let's briefly discuss it to see if it makes sense to you

2023-07-31 12:06 UTC, ysherstyuk commented on functions/spark_session.py
> +        df = read_session.read.format(table_definition['type']).schema(table_definition['columns']).option('header', True).option("quote", '"').option("multiline", 'True').load(table_location)
What exactly is happening in the quote and multiline part?

2023-07-31 15:02 UTC, SKruthoff commented on functions/spark_session.py
> +        df = read_session.read.format(table_definition['type']).schema(table_definition['columns']).option('header', True).option("quote", '"').option("multiline", 'True').load(table_location)
This is to adapt to some csv format that is used within ecoinvent. The multiline = True is there since the description of products in ecoinvent can have linebreaks.

2023-07-31 15:04 UTC, SKruthoff commented on ecoInvent.py
>  generate_table('geographies_transform')
Which ones are not added? My goal is to clean up ecoInvent in a different Pull Request

2023-07-31 15:06 UTC, SKruthoff commented on functions/data_quality.py
> +    if re.match(format, col):
it could be both ways. I chose to do it this way because then we can easily use it in the filter function. Because the goal is to find rows that do not match the format, we can say we do not want to see them if they match the format. this means that if we have a match, we return false to not return the rows in the count

2023-08-01 12:07 UTC, ysherstyuk approved these changes
LGTM

2023-08-01 15:06 UTC, merged