8 signaling issues to monitor in powerbi or in other functionality part of 11
2DegreesInvesting/tiltDataPipelines pull request #44
Opened 2023-09-11 14:20 UTC by ysherstyuk

2023-09-13 11:50 UTC, SKruthoff requested changes

2023-09-13 11:50 UTC, SKruthoff commented on signalling_quality_checks.py
> +from functions.spark_session import read_table, create_spark_session
In general I would split this up into two parts:
One part should be the storage of the quality rules and the other file should be the check of those quality rules.

2023-09-13 11:50 UTC, SKruthoff commented on signalling_functions.py
> +from pyspark.sql import DataFrame, SparkSession
This file looks good. I would move it to the functions folder though, because that would align with the principle that we have all of the generic functions in that folder.

2023-09-13 11:50 UTC, SKruthoff commented on functions/processing.py
> +        # to integer
Remove the following three lines of code

2023-09-13 11:50 UTC, SKruthoff commented on signalling_quality_checks.py
> +        df.show(10)
It is better to not have any .show or print statements in as it slows down the actual pipelines and it only helps us when debugging

2023-09-13 11:50 UTC, SKruthoff commented on signalling_quality_checks.py
> +            value_list = tables_list.get('value_list')
I would move the values such as value_list, range_start and range_end as they are only filled for certain checks and not generically

2023-09-13 11:50 UTC, SKruthoff commented on signalling_quality_checks.py
> +    # Check if all columns are filles
Check if the comments and line breaks are needed meaning that we still need to add something

2023-09-13 14:34 UTC, SKruthoff requested changes
Structure looks good, but I think there are some work we need to do in the check_signalling_issues function

2023-09-13 14:34 UTC, SKruthoff commented on functions/signalling_functions.py
> +            tables_list = signalling_checks_dictionary[table_name][0]
This is fine for now, but this will not work if we have multiple checks per table.

2023-09-13 14:34 UTC, SKruthoff commented on functions/signalling_functions.py
> +
Insert the functionality to write a table here

2023-09-13 14:34 UTC, SKruthoff commented on functions/signalling_functions.py
> +    for table_name in table_name_list:
Do we have to loop here over the full list? Because in the signalling tables.py we already loop over all tables. So if we keep that loop in here, for every table in that list we check for all tables. The functionality as the function suggests it that it only checks it for one table.

2023-09-13 14:34 UTC, SKruthoff commented on signalling_tables.py
> +table_name_list = ['categories_raw', 'categories_companies_raw', 'categories_sector_ecoinvent_delimited_raw', 'clustered_raw', 'clustered_delimited_raw', 'companies_raw', 'consequential_ao_raw',
In my opinion this can be in the signalling_quality_checks.py file. Good to specify it in the same file that you are looping over

2023-09-14 09:00 UTC, ysherstyuk commented on functions/signalling_functions.py
> +            tables_list = signalling_checks_dictionary[table_name][0]
What would you suggest to implement instead?

2023-09-15 07:27 UTC, SKruthoff approved these changes
Looks good

2023-09-15 07:27 UTC, merged