Implemented checks 1, 3, 5 and 8
2DegreesInvesting/tiltDataPipelines pull request #61
Opened 2023-10-03 11:20 UTC by ysherstyuk

Checks implemented and already implemented before:
1. company name should have company id
2. company ids can be different
3. company name should be unique -> Found at bundesbank matching
4. country is valid name/abbreviation -> un format
5. country should be not null
8. main activity in list and not null

2023-10-03 11:45 UTC, SKruthoff requested changes

2023-10-03 11:45 UTC, SKruthoff commented on functions/tables.py
> +                StructField('company_name', StringType(), False),
We should not enforce this in the landingzone. It is possible that a column has null values in the landingzone that we eliminate this in the processing from landingzone to the raw layer. This is the same reasoning that all columns in the landingzone should be string types. So that we still have the options to convert, format and filter between landingzone and raw layer to fix any issues that might exist in the source dataset.

2023-10-03 11:45 UTC, SKruthoff commented on functions/tables.py
> +            'quality_checks': [['unique',['companies_id', 'company_name']]]
I am not sure that we are using this correctly. What you specified here is that the combination of the companies_id and company_name have to be unique. If we wanted to implement the check that the company_name should be unique it should look like this:
[['unique',['companies_id']]['unique', ['company_name']]]
I am not sure that we want this though, because we know that this is not the case and we already included it in the singalling checks

2023-10-03 13:18 UTC, ysherstyuk commented on functions/tables.py
> +                StructField('company_name', StringType(), False),
You're right

2023-10-03 13:25 UTC, ysherstyuk commented on functions/tables.py
> +            'quality_checks': [['unique',['companies_id', 'company_name']]]
True that

2023-10-11 06:49 UTC, SKruthoff requested changes

2023-10-11 06:49 UTC, SKruthoff commented on functions/tables.py
> +                StructField('ep_country', StringType(), True),
This should be False aligning with the other comment about the landingzone.

2023-10-11 07:22 UTC, SKruthoff approved these changes
Looks good.

2023-10-11 07:22 UTC, merged