Monitoring and hive tables
2DegreesInvesting/tiltDataPipelines pull request #75
Opened 2023-10-11 13:58 UTC by SKruthoff

This is the implementation of the creation of hive tables and monitoring check after writing the table. I had to replace the check_signalling_issues functionality to the spark_session.py, because otherwise a circular import would have been created. This would have been the case since we would have imported a function from spark_session to signalling_functions and the other way around. Additionally, I had to change that we are passing the dataframe and not the name of the name of the dataframe in the consistency check to also avoid a circular import.

2023-10-12 14:29 UTC, SKruthoff commented
Hi, 
I have implemented the other function in the signalling functions again. I also streamlined the usage and updating of the monitoring values tables in our function. This led me to realize that we have an issue with reading partitioned tables, so I also renamed the partition variables to either partition_name or partition_column. 

Lets take some time to discuss on Monday to go through this as this became quite an extensive pull request unintentionally.

2023-10-16 12:43 UTC, ysherstyuk requested changes
I had a few questions:) We can discuss them during the check-in

2023-10-16 12:43 UTC, ysherstyuk commented on functions/signalling_functions.py
> -    col_order = ['check_id', 'table_name', 'column_name', 'check_name', 'total_count', 'valid_count']
If you remove table_name from the output table on the check that should run for all tables, how do you know which table is being checked?
Maybe I missed that, but why do we want to remove the table name?

2023-10-16 12:43 UTC, ysherstyuk commented on functions/signalling_functions.py
>      Calculates the count of filled and total values for each column in a DataFrame.
If you remove table_name, it needs to be adjusted in the parameters and returns of the docstring

2023-10-16 12:43 UTC, ysherstyuk commented on functions/spark_session.py
> +    # Dyanmic Overwrite mode makes sure that other parts of a partition that are not processed are not overwritten as well.
typo Dynamic

2023-10-16 12:43 UTC, ysherstyuk commented on functions/spark_session.py
> +    # Dyanmic Overwrite mode makes sure that other parts of a partition that are not processed are not overwritten as well.
It would be great to get some extra explanation on the dynamic overwrite mode, just for my understanding:)

2023-10-16 12:43 UTC, ysherstyuk commented on functions/spark_session.py
> +    dummy_signalling_df = read_table(spark_session,'dummy_quality_check')
Is it better to create a dummy table first? Did you run some tests?

2023-10-16 12:43 UTC, ysherstyuk commented on functions/tables.py
> +            'partition_by' : 'table_name',
Why are we partitioning monitoring values dataframe?

2023-10-18 08:29 UTC, ysherstyuk approved these changes
LGTM

2023-10-20 06:02 UTC, merged